FROM amazon/aws-for-fluent-bit:build as builder
COPY ./scripts/dockerfiles/Dockerfile.build /Dockerfile.1.build

# Build Fluent Bit with release compiler flags
RUN cmake -DFLB_RELEASE=On \
          -DFLB_TRACE=Off \
          -DFLB_JEMALLOC=On \
          -DFLB_TLS=On \
          -DFLB_SHARED_LIB=Off \
          -DFLB_EXAMPLES=Off \
          -DFLB_HTTP_SERVER=On \
          -DFLB_IN_SYSTEMD=On \
          -DFLB_OUT_KAFKA=On \
          -DFLB_ARROW=On ..

RUN make -j $(getconf _NPROCESSORS_ONLN)
RUN install bin/fluent-bit /fluent-bit/bin/

# Build lightweight release image
FROM public.ecr.aws/amazonlinux/amazonlinux:2

# Ensure default user shell timeout is configured (CIS_AMAZON2_4.5.3.2)
ENV TMOUT=600
RUN echo "TMOUT=${TMOUT}" >> /etc/profile && \
    echo "readonly TMOUT" >> /etc/profile && \
    echo "export TMOUT" >> /etc/profile

# Ensure default user umask is configured (CIS_AMAZON2_4.5.3.3)
RUN echo "umask 027" >> /etc/profile && \
    echo "umask 027" >> /etc/bashrc

RUN yum upgrade -y && yum install -y \
          # This package is needed to verify if this OpenSSL version is FIPS compliant
          # openssl11 \
          openssl11-devel \
          cyrus-sasl-devel \
          pkgconfig \
          systemd-devel \
          zlib-devel \
          libyaml \
          tar \
          nc && rm -fr /var/cache/yum

# When enabling home audit fails on "Ensure Root Path Integrity (CIS_AMAZON2_6.2.8)"
# It's needed to install GO in the final image if necessary to veryify the build binaries are fips complaint
# Command to test: 
# - go tool nm /fluent-bit/bin/fluent-bit | grep FIPS
# - go tool nm /fluent-bit/kinesis.so | grep FIPS
# - go tool nm /fluent-bit/firehose.so | grep FIPS
# - go tool nm /fluent-bit/cloudwatch.so | grep FIPS

# ENV HOME /home
# ENV GOEXPERIMENT=boringcrypto
# ENV CGO_ENABLED=1
# RUN curl -sL -o /bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
# RUN chmod +x /bin/gimme

# # Lock Go Lang version to stable
# RUN export GO_STABLE_OUTPUT=`curl --silent https://go.dev/VERSION?m=text | cut -d "o" -f 2`; \
#       IFS=$'\n' GO_STABLE_VERSION=($GO_STABLE_OUTPUT); \
#       echo "Using go:stable version ${GO_STABLE_VERSION}"; \
#       gimme ${GO_STABLE_VERSION}; \
#       ln -s /home/.gimme/versions/go${GO_STABLE_VERSION}.linux.arm64 /home/.gimme/versions/gostable.linux.arm64; \
#       ln -s /home/.gimme/versions/go${GO_STABLE_VERSION}.linux.amd64 /home/.gimme/versions/gostable.linux.amd64
# ENV PATH ${PATH}:/home/.gimme/versions/gostable.linux.arm64/bin:/home/.gimme/versions/gostable.linux.amd64/bin
# RUN go version


COPY --from=builder /fluent-bit /fluent-bit
COPY --from=aws-fluent-bit-plugins:latest /kinesis-streams/bin/kinesis.so /fluent-bit/kinesis.so
COPY --from=aws-fluent-bit-plugins:latest /kinesis-firehose/bin/firehose.so /fluent-bit/firehose.so
COPY --from=aws-fluent-bit-plugins:latest /cloudwatch/bin/cloudwatch.so /fluent-bit/cloudwatch.so
RUN mkdir -p /fluent-bit/licenses/fluent-bit
RUN mkdir -p /fluent-bit/licenses/firehose
RUN mkdir -p /fluent-bit/licenses/cloudwatch
RUN mkdir -p /fluent-bit/licenses/kinesis
COPY THIRD-PARTY /fluent-bit/licenses/fluent-bit/
COPY --from=aws-fluent-bit-plugins:latest /kinesis-firehose/THIRD-PARTY \
    /kinesis-firehose/LICENSE \
    /fluent-bit/licenses/firehose/
COPY --from=aws-fluent-bit-plugins:latest /cloudwatch/THIRD-PARTY \
    /cloudwatch/LICENSE \
    /fluent-bit/licenses/cloudwatch/
COPY --from=aws-fluent-bit-plugins:latest /kinesis-streams/THIRD-PARTY \
    /kinesis-streams/LICENSE \
    /fluent-bit/licenses/kinesis/
COPY AWS_FOR_FLUENT_BIT_VERSION /AWS_FOR_FLUENT_BIT_VERSION
ADD ecs /ecs/

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Optional Metrics endpoint
EXPOSE 2020

# Entry point
CMD /entrypoint.sh
